### ISSUE TITLE
Fix fatal error because of class not found

### ISSUE THREAD

**Issue by programarivm** [programarivm/php-chess#34]
```
PHP Fatal error:  Uncaught Error: Class 'Chess\StringToBoard' not found in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Game.php:283
Stack trace:
#0 /home/standard/projects/chess-server/src/Socket.php(110): Chess\Game->loadFen()
#1 /home/standard/projects/chess-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(75): ChessServer\Socket->onMessage()
#2 /home/standard/projects/chess-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(131): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#3 /home/standard/projects/chess-server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\WebSocket\WsServer->Ratchet\WebSocket\{closure}()
#4 /home/standard/projects/chess-server/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData()
#5 /home/standard/projects/chess-server/vendor/cboden/ratchet/src/Ratchet/WebSocket/WsServer.php(153): Ratchet\RFC6455\Messaging\MessageBuffer->onData()
#6 /home/standard/projec in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Game.php on line 283
```

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/php-chess/pull/35
