### ISSUE TITLE
Pieces can't be selected after loading a FEN string

### ISSUE THREAD

**Issue by programarivm** [programarivm/php-chess#37]
The first position of the Kaufman test throws an error when selecting a black piece after a white piece is moved.

1rbq1rk1/p1b1nppp/1p2p3/8/1B1pN3/P2B4/1P3PPP/2RQ1R1K w - - bm Nf6+

![position-01](https://user-images.githubusercontent.com/4062000/131578898-79766ebb-265d-4c75-a60b-e214fc559187.png)

```
$ php cli/ws-server.php 
Welcome to PHP Chess Server
Commands available:
/accept {"id":"id"} Accepts a friend request to play a game.
/ascii Prints the ASCII representation of the game.
/castling Gets the castling status.
/captures Gets the pieces captured by both players.
/fen Prints the FEN string representation of the game.
/heuristicpicture Takes a balanced heuristic picture of the current game.
/history The current game's history.
/ischeck Finds out if the game is in check.
/ismate Finds out if the game is over.
/piece {"position":"string"} Gets a piece by its position on the board.
/pieces {"color":["w","b"]} Gets the pieces on the board by color.
/playfen {"fen":"string"} Plays a chess move in shortened FEN format.
/quit Quits a game.
/start {"mode":["analysis","fen","playfriend"],"fen":"string","color":["w","b"],"min":"int"} Starts a new game.
/status The current game status.

Listening to commands...
PHP Notice:  Trying to get property 'move' of non-object in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php on line 606
PHP Notice:  Trying to get property 'position' of non-object in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php on line 606
PHP Notice:  Trying to get property 'next' of non-object in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php on line 606
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Chess\Board::getPieceByPosition() must be of the type string, null given, called in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php on line 606 and defined in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php:361
Stack trace:
#0 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php(606): Chess\Board->getPieceByPosition()
#1 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php(818): Chess\Board->undoCastle()
#2 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php(532): Chess\Board->leavesInCheck()
#3 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php(562): Chess\Board->isLegalMove()
#4 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/FEN/AbstractStringToPgn.php(91): Chess\Board->play()
#5 /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Game.php(321): C in /home/standard/projects/chess-server/vendor/programarivm/php-chess/src/Board.php on line 361
```

**Comment by programarivm** [comment]
Merged PR https://github.com/programarivm/php-chess/pull/38
